[tools]
ffmpeg = "latest"
gh = "latest"
java = "zulu-21"
node = "22"
python = "3.11"
ruby = "3.3"
shellcheck = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }

[settings]

[settings.ruby]
compile = false
