#Bash Profile

# Load MITRE specific proxy if applicable
if [ -f ~/.mitre_proxy ]; then
    source ~/.mitre_proxy
fi

# Load Bash Aliases if applicable
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

#Android SDK
export ANDROID_SDK=~/Library/Android/sdk
export ANDROID_SDK_PLATFORM=$ANDROID_SDK/platform-tools
export ANDROID_SDK_BUILD=$ANDROID_SDK/build-tools
export ANDROID_SDK_TOOLS=$ANDROID_SDK/tools
export ANDROID_HOME=$ANDROID_SDK


export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home

#Main Variables
export PATH="$ANDROID_SDK:$ANDROID_SDK_PLATFORM:$ANDROID_SDK_BUILD:$ANDROID_SDK_TOOLS:$JAVA_HOME:$JAVA_HOME/bin:$PATH"

# Ignore warning about ZSH upgrade in OSX 
export BASH_SILENCE_DEPRECATION_WARNING=1

#Maven if applicable
if [ -d ~/Library/Maven/ ]; then
    export MAVEN_HOME=~/Library/Maven/3.5.2
    export MAVEN_HOME_BIN=$MAVEN_HOME/bin
    export PATH="$PATH:$MAVEN_HOME_BIN"
fi

# Gradle if applicable
if [ -d ~/Library/Gradle/ ]; then
    export GRADLE_HOME=~/Library/Gradle/8.10.2
    export GRADLE_HOME_BIN=$GRADLE_HOME/bin
    export PATH="$PATH:$GRADLE_HOME_BIN"
fi

#PS1
PS1="["
PS1+="\[\e[1;34m\]" #blue color for line below
PS1+="\u"           #current user
PS1+="\[\033[0m\]"  #white for @
PS1+="@"
PS1+="\[\e[0;33m\]"   #yellow for host
PS1+="\h"
PS1+="\[\033[0m\]"  #white for rest
PS1+="] \w/ $ "
export PS1
#Alternative
#export PS1="\u@$(scutil --get ComputerName): \w $ "

